Repository sendgrid/smtpapi-python, pull requests merged in 2018-10, with the labels that each got.

#66 Update LICENSE.txt
  LICENSE.txt
  test/__init__.py
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#52 Update travis - add codecov
  .travis.yml
Labels: difficulty: easy, status: ready for deploy, type: sendgrid enhancement

#75 fixed Travis, converted README and version as file
  .gitignore
  .travis.yml
  MANIFEST.in
  README.md
  README.rst
  VERSION.txt
  setup.py
  smtpapi/__init__.py
  test/__init__.py
  test/test_project.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#65 Fix "Complexity" issue in examples/example.py
  examples/example.py
Labels: difficulty: easy, status: waiting for feedback, type: community enhancement

#77 add first-timers.md with guide for newcomers
  FIRST-TIMERS.md
  static/img/github-fork.png
  static/img/github-sign-up.png
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#87 PEP8 fix
  examples/example.py
  smtpapi/__init__.py
  test/__init__.py
  test/test_lisence.py
  test/test_project.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#80 Adding CHANGELOG auto generation script
  changes.py
Labels: difficulty: hard, hacktoberfest, status: hacktoberfest approved, status: work in progress

#79 Update contribution to use Gitflow workflow
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: docs update
