Repository sendgrid/smtpapi-python, pull requests merged in 2020-08, with the labels that each got.

#105 chore: update GitHub branch references to use HEAD
  CONTRIBUTING.md
  Dockerfile
  FIRST-TIMERS.md
  README.rst
  twilio_sendgrid_logo.png
Labels: status: code review request

#70 docs: Correct *.md files using Grammarly
  CONTRIBUTING.md
  README.rst
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for merge

#72 docs: Fix .md with Grammar.ly
  CHANGELOG.md
  CONTRIBUTING.md
  README.rst
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress
