Repository sendgrid/smtpapi-python, pull requests merged in 2020-02, with the labels that each got.

#88 docs: Fix typos and grammatical errors
  USAGE.md
Labels: difficulty: easy, status: hacktoberfest approved, status: work in progress

#53 fix: "similar-code" issue in smtpapi/__init__.py
  LICENSE.md
  smtpapi/__init__.py
Labels: difficulty: easy, status: work in progress, type: sendgrid enhancement

#104 chore: add Python 3.8 to Travis
  .travis.yml
  README.rst
Labels: status: code review request
